#!/usr/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

# BSPWM configuration
# bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           7
bspc config top_padding          28
bspc config bottom_padding       8
bspc config left_padding         8
bspc config right_padding        8
#bspc config single_monocle       false
# bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_by_distance    true
bspc config focus_follows_pointer true
# bspc config history_aware_focus  true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# dual monitor
# find out names with arandr or xrandr

# change this to left to use the monitor on left side   ->    --right-of eDP fi
if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --right-of eDP
fi

bspc monitor eDP -d 1 2 3 4
bspc monitor HDMI-A-0 -d 5 6 7 8

# BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	   "#f2ae49"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

#Fullscreen applications
#bspc rule -a Vlc state=fullscreen
#bspc rule -a Gimp state=fullscreen

#Fix Mouse curoor on startup
#xsetroot -cursor_name left_ptr

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating

#Tiled applications
bspc rule -a Xfce4-settings-manager state=tiled

#open applications on specific workspaces
#bspc rule -a Firefox desktop='^1' follow=on
#bspc rule -a Google-chrome desktop='^1' follow=on
#bspc rule -a Chromium desktop='^1'  follow=on
#bspc rule -a Subl desktop='^2' follow=on
#bspc rule -a Atom desktop='^2' follow=on
#bspc rule -a Steam desktop='^5'
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Vivaldi-stable desktop='^6' follow=on
#bspc rule -a Vivaldi-snapshot desktop='^6' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
#bspc rule -a Thunar desktop='^8' follow=on
#bspc rule -a discord desktop='^9' follow=on
#bspc rule -a Spotify desktop='^10' follow=on


#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window



# third monitor
# find out names with arandr or xrandr
#if [[ $(xrandr -q | grep 'HDMI3 connected') ]]; then
#  xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI3 --mode 1920x1080 --rotate normal --right-of eDP
#fi



#----------------------------------------- eof -----------------------------------------
